# Generated by Django 6.1 on 2026-09-01 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('protocols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformedExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_exercises', to='catalog.exercisedefinition')),
                ('exercise_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_exercises', to='protocols.exerciseprescription')),
            ],
            options={
                'verbose_name': 'performed exercise',
                'verbose_name_plural': 'performed exercises',
            },
        ),
        migrations.CreateModel(
            name='PerformedSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('duration_s', models.IntegerField(blank=True, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_sets', to='observations.performedexercise')),
            ],
            options={
                'verbose_name': 'performed set',
                'verbose_name_plural': 'performed sets',
            },
        ),
        migrations.CreateModel(
            name='PerformedRep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rep_index', models.IntegerField()),
                ('performed_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_reps', to='observations.performedset')),
            ],
            options={
                'verbose_name': 'performed rep',
                'verbose_name_plural': 'performed reps',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('mixed', 'Mixed')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'training session',
                'verbose_name_plural': 'training sessions',
            },
        ),
        migrations.AddField(
            model_name='performedexercise',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_exercises', to='observations.trainingsession'),
        ),
        migrations.AddIndex(
            model_name='performedset',
            index=models.Index(fields=['performed_exercise', 'created_at'], name='perfset_exercise_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='performedrep',
            constraint=models.UniqueConstraint(fields=('performed_set', 'rep_index'), name='perfrep_set_rep_index_uniq'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'created_at'], name='trainsess_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='performedexercise',
            index=models.Index(fields=['training_session', 'created_at'], name='perfex_session_created_idx'),
        ),
    ]
