# Generated by Django 6.1 on 2026-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_trainingsession_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('mobility', 'Mobility'), ('mixed', 'Mixed')], max_length=8),
        ),
    ]
