# Generated by Django 6.1 on 2026-09-02 09:36

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='who first added this movement; null for the seeded and admin-created rows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_definitions_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='exercisedefinition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='exercisedef_name_ci_unique'),
        ),
    ]
