# Generated by Django 6.1 on 2026-09-03 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_exercisedefinition_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedefinition',
            name='bar_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='weight of the bar, carriage or sled before any plates; null until this movement has been asked about', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='exercisedefinition',
            name='sides',
            field=models.PositiveSmallIntegerField(blank=True, help_text='how many sides the typed weight goes on: 2 for a barbell, 1 for a stack or a sled', null=True),
        ),
        migrations.AddConstraint(
            model_name='exercisedefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bar_kg__isnull', True), ('sides__isnull', True)), models.Q(('bar_kg__isnull', False), ('sides__isnull', False)), _connector='OR'), name='exercisedef_loading_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='exercisedefinition',
            constraint=models.CheckConstraint(condition=models.Q(('sides__isnull', True), models.Q(('sides__gte', 1), ('sides__lte', 2)), _connector='OR'), name='exercisedef_sides_1_or_2'),
        ),
        migrations.AddConstraint(
            model_name='exercisedefinition',
            constraint=models.CheckConstraint(condition=models.Q(('bar_kg__isnull', True), ('bar_kg__gte', 0), _connector='OR'), name='exercisedef_bar_kg_not_negative'),
        ),
    ]
