# Generated by Django 6.1 on 2026-09-01 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'exercise prescription',
                'verbose_name_plural': 'exercise prescriptions',
            },
        ),
    ]
