# Generated by Django 6.1 on 2026-09-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='type',
            field=models.CharField(max_length=8),
        ),
    ]
