# Generated by Django 6.1 on 2026-09-01 15:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_started_at(apps, schema_editor):
    """started_at is non-null with a callable default, so every existing row was
    just stamped with the moment this migration ran. The row's own created_at is
    the only record of when that training happened; without this, the whole
    history claims to have been trained during the deploy."""
    TrainingSession = apps.get_model('observations', 'TrainingSession')
    TrainingSession.objects.update(started_at=models.F('created_at'))


def backfill_ended_at(apps, schema_editor):
    """A null ended_at reads as "in progress", which no historical session is.
    Closing each one where it started leaves none open, and none in breach of
    the check constraint added below."""
    TrainingSession = apps.get_model('observations', 'TrainingSession')
    TrainingSession.objects.update(ended_at=models.F('started_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_trainingsession_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainingsession',
            name='trainsess_user_created_idx',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='null while the session is in progress', null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='when the training actually happened; created_at is when the row was written'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='type',
            field=models.CharField(default='mixed', max_length=8),
        ),
        migrations.RunPython(backfill_started_at, migrations.RunPython.noop),
        migrations.RunPython(backfill_ended_at, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'started_at'], name='trainsess_user_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='trainsess_ended_after_started'),
        ),
    ]
