# Generated by Django 6.1 on 2026-09-03 11:03

from django.db import migrations, models
from django.db.models.functions import Coalesce


def backfill_ended_at(apps, schema_editor):
    """A null ended_at reads as "in progress", which no exercise already recorded
    is. Each one is closed at its last set, falling back to its own created_at
    when it never got one.

    Not timezone.now(): the whole training log would claim to have finished
    during the deploy, which is the mistake started_at's backfill was written to
    avoid. Not created_at alone either: a block that took twenty minutes would
    record itself as instantaneous, and created_at is already the answer for the
    blocks that have nothing better. Both branches satisfy the check constraint
    added below, because a set is always created after its exercise."""
    PerformedExercise = apps.get_model('observations', 'PerformedExercise')
    PerformedSet = apps.get_model('observations', 'PerformedSet')
    last_set_at = models.Subquery(
        PerformedSet.objects
        .filter(performed_exercise=models.OuterRef('pk'))
        .order_by('-created_at')
        .values('created_at')[:1]
    )
    PerformedExercise.objects.update(
        ended_at=Coalesce(last_set_at, models.F('created_at'))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_exercisedefinition_created_by_and_more'),
        ('observations', '0004_remove_trainingsession_trainsess_user_created_idx_and_more'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performedexercise',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='null while the exercise is being recorded', null=True),
        ),
        # Before the constraint, which the backfilled rows have to satisfy.
        migrations.RunPython(backfill_ended_at, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='performedexercise',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('created_at')), _connector='OR'), name='perfex_ended_after_created'),
        ),
    ]
