# Generated by Django 6.1 on 2026-09-04 14:38

from django.db import migrations


def delete_empty_sessions(apps, schema_editor):
    """A session with no exercises in it is not a workout, and from now on the
    app will not file one: ending an empty session deletes it rather than
    stamping it into history. This is that same rule applied once to what is
    already recorded, so that the history has no empty rows anywhere in it and
    not only from here forward.

    Empty means no PerformedExercise rows — not "no sets". An ended session's
    exercises always have sets anyway, so counting one level further down would
    be a slower way of asking the same question.

    Open sessions go too. The narrower sweep — only sessions with ended_at set —
    was offered and declined: a session open on a phone at the moment this runs,
    with nothing logged into it yet, disappears from under its user, and the tab
    falls back to the Start screen with no explanation. That was accepted in
    exchange for a history with no empty rows in it at all.

    The cascade reaches nothing: a session with no exercises has no sets and no
    reps beneath it, so the only rows this deletes are the sessions themselves.

    The reverse is a noop because deleted rows do not come back. Migrating back
    to 0005 will succeed and restore nothing, which is honest."""
    TrainingSession = apps.get_model('observations', 'TrainingSession')
    TrainingSession.objects.filter(performed_exercises__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_performedexercise_ended_at_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_empty_sessions, migrations.RunPython.noop),
    ]
