# Generated by Django 6.1 on 2026-09-02 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('kind', models.CharField(choices=[('idea', 'Idea'), ('bug', 'Bug'), ('other', 'Other')], default='idea', max_length=8)),
                ('page_path', models.CharField(blank=True, default='', help_text='where the writer was when the thought arrived, e.g. /current-session', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='null means the note is still outstanding', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback note',
                'verbose_name_plural': 'feedback notes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='feednote_user_created_idx')],
            },
        ),
    ]
